Repository GOSOPT-CDS-TEAM-APP5/Lotte-Cinema-AOS, pull requests merged in 2023-05, with the labels that each got.

#12 영화 시간 선택 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/lottecinemaaos/data/entity/Calendar.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/entity/TimeTable.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/model/HomeLottePick.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/model/MovieChart.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/movietime/MovieTimeSelectionActivity.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/movietime/MovieTimeSelectionCalendarAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/movietime/MovieTimeSelectionChipAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/movietime/MovieTimeSelectionTimeTableAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/movietime/MovieTimeSelectionViewModel.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/theater/CinemaSelectionActivity.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/theater/CinemaSelectionChipAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/theater/CinemaSelectionViewModel.kt
  app/src/main/res/drawable/shape_g100_r4_rect.xml
  app/src/main/res/layout/activity_cinema_selection.xml
  app/src/main/res/layout/activity_movie_time_selection.xml
  app/src/main/res/layout/item_selection_date.xml
  app/src/main/res/layout/item_selection_theater_timetable.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🐱 지영

#11 #9 홈 화면 영화차트 RV 서버 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/lottecinemaaos/data/datasource/remote/HomeMovieChartRemoteDataSource.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/entity/HomeLottePick.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/entity/MovieChart.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/model/ApiFactory.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/model/response/ResponseHomeMovieChartDto.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/repository/HomeMovieChartRepository.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/service/LotteCinemaHomeService.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/repository/HomeMovieChartRepositoryImpl.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/home/CinemaHomeFragment.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/home/CinemaHomeMovieChartRVAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/home/CinemaHomePickRVAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/home/CinemaHomeViewModel.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/theater/CinemaSelectionActivity.kt
  app/src/main/res/drawable/img_home_movie_poster1.png
  app/src/main/res/drawable/img_home_movie_poster2.png
  app/src/main/res/layout/item_home_movie_chart.xml
Labels: 🐰 서현

#10 #4 영화 정보 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/lottecinemaaos/domain/model/Poster.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/model/Trailer.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailActivity.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailPosterAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailTrailerAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailViewModel.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/home/CinemaHomeFragment.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/selection/main/MainActivity.kt
  app/src/main/res/drawable/drawable_resize.xml
  app/src/main/res/drawable/img_audiencegraph.png
  app/src/main/res/drawable/img_banner.png
  app/src/main/res/drawable/img_big_teaser.png
  app/src/main/res/drawable/img_cast1.png
  app/src/main/res/drawable/img_cast2.png
  app/src/main/res/drawable/img_cast3.png
  app/src/main/res/drawable/img_cast4.png
  app/src/main/res/drawable/img_cast5.png
  app/src/main/res/drawable/img_fab.png
  app/src/main/res/drawable/img_fab_background.png
  app/src/main/res/drawable/img_front_gog_poster.png
  app/src/main/res/drawable/img_icon_charlotte.png
  app/src/main/res/drawable/img_icon_cinecomfort.png
  app/src/main/res/drawable/img_icon_cinecouple.png
  app/src/main/res/drawable/img_icon_cinefamily.png
  app/src/main/res/drawable/img_icon_colorium.png
  app/src/main/res/drawable/img_icon_heart.png
  app/src/main/res/drawable/img_icon_ratingstar.png
  app/src/main/res/drawable/img_icon_share.png
  app/src/main/res/drawable/img_icon_splex.png
  app/src/main/res/drawable/img_icon_super4d.png
  app/src/main/res/drawable/img_icon_supers.png
  app/src/main/res/drawable/img_icon_toolbarbackbtn.png
  app/src/main/res/drawable/img_icon_vector.png
  app/src/main/res/drawable/img_poster1.png
  app/src/main/res/drawable/img_stillcut1.png
  app/src/main/res/drawable/img_stillcut2.png
  app/src/main/res/drawable/img_stillcut3.png
  app/src/main/res/drawable/img_stillcut4.png
  app/src/main/res/drawable/img_stillcut5.png
  app/src/main/res/drawable/img_trailer1.png
  app/src/main/res/drawable/img_trailer2.png
  app/src/main/res/drawable/img_trailer3.png
  app/src/main/res/drawable/img_trailer4.png
  app/src/main/res/drawable/img_trailer5.png
  app/src/main/res/drawable/rectangle_style.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_movie_detail.xml
  app/src/main/res/layout/fragment_cinema_home.xml
  app/src/main/res/layout/item_detail_poster.xml
  app/src/main/res/layout/item_detail_trailer.xml
  app/src/main/res/layout/view_movie_detail_information.xml
  app/src/main/res/layout/view_movie_detail_trailer.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 🐥 민정

#16 #14 영화 정보 뷰 서버통신 구현
  app/src/main/java/com/sopt/lottecinemaaos/data/datasource/remote/HomeMovieChartRemoteDataSource.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/datasource/remote/MovieDetailRemoteDataSource.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/entity/Poster.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/entity/Trailer.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/model/ApiFactory.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/model/response/ResponseMovieDetailDto.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/repository/ExampleRepositoryImpl.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/repository/HomeMovieChartRepositoryImpl.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/repository/MovieDetailRepositoryImpl.kt
  app/src/main/java/com/sopt/lottecinemaaos/data/service/MovieDetailService.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/model/Poster.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/repository/ExampleRepository.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/repository/HomeMovieChartRepository.kt
  app/src/main/java/com/sopt/lottecinemaaos/domain/repository/MovieDetailRepository.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailActivity.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailPosterAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailTrailerAdapter.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieDetailViewModel.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/detail/MovieInformationViewModel.kt
  app/src/main/java/com/sopt/lottecinemaaos/presentation/home/CinemaHomeViewModel.kt
  app/src/main/res/drawable/resize_poster1.xml
  app/src/main/res/drawable/resize_stillcut1.xml
  app/src/main/res/drawable/resize_stillcut2.xml
  app/src/main/res/drawable/resize_stillcut3.xml
  app/src/main/res/drawable/resize_stillcut4.xml
  app/src/main/res/drawable/resize_stillcut5.xml
  app/src/main/res/layout/activity_movie_detail.xml
  app/src/main/res/layout/item_detail_poster.xml
  app/src/main/res/layout/view_movie_detail_information.xml
Labels: 🐥 민정
